### ISSUE TITLE
Generalize into common activity logging tool

### ISSUE THREAD

**Issue by cowbellerina** [exove-danny/slack-stairs-logger#1]
Could this be generalized into a tool that would support custom activity types instead of just stairs?

I already do the stairs every day but - in the spirit of internet of shit - would like to log the amount of visits to the toilet, cigarettes smoked, and sexual harassment attempts made.

Using the tool could look like

```
/log log stairs
```

```
/log list stairs
```

where the second param would be the activity type.

Any thoughts?

**Comment by exove-danny** [comment]
Great idea and something we could definitely look into in the future :)
